version: '3'
services:
  app:
    image: server
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
