version: '3'
services:
  app:
    image: server
    ports:
      - 5000:5000
  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: ayub
        POSTGRES_PASSWORD: ayub
        POSTGRES_DB: yetu
